# Make Review Dataset

Notebook ini bertujuan mengidentifikasi data dengan tingkat kepercayaan (confidence score) rendah dari hasil klasifikasi sentimen IndoBERT.

Data dengan confidence < 70% akan direview dan dikoreksi secara manual sebelum digunakan pada proses fine-tuning model.

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv("/content/drive/MyDrive/KaburAjaDulu/data/sentiment_results.csv")

Mounted at /content/drive

In [3]:
low_conf = df[df["confidence"] < 70].copy()
high_conf = df[df["confidence"] >= 70].copy()

print(f"Confidence >= 70% : {len(high_conf)}")
print(f"Confidence < 70%  : {len(low_conf)}")

Confidence >= 70% : 16303
Confidence < 70%  : 2511

In [4]:
high_conf["label_final"] = high_conf["sentiment"]

In [5]:
low_conf["label_final"] = low_conf["sentiment"]

low_conf = (
    low_conf
    .sort_values("confidence", ascending=True)
    .reset_index(drop=True)
)

In [6]:
low_conf["sentiment"].value_counts()

sentiment
negatif    938
positif    814
netral     759
Name: count, dtype: int64

In [7]:
(
    low_conf["sentiment"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

sentiment
negatif    37.36
positif    32.42
netral     30.23
Name: proportion, dtype: float64

In [9]:
low_conf[[
        "full_text",
        "clean_text",
        "sentiment",
        "confidence",
        "label_final"
    ]].to_csv("review_low_confidence.csv",index=False)

In [10]:
high_conf[[
        "full_text",
        "clean_text",
        "sentiment",
        "confidence",
        "label_final",
        "platform"
    ]].to_csv("high_confidence_data.csv",index=False)